#La configuracion del application.yml, tiene prioridad sobre la configuracion de la clase

#resilience4j.circuitbreaker.configs.defecto.sliding-window-size=6
#resilience4j.circuitbreaker.configs.defecto.failure-rate-threshold=50
#resilience4j.circuitbreaker.configs.defecto.wait-duration-in-open-state=20s
#resilience4j.circuitbreaker.configs.defecto.permitted-number-of-calls-in-half-open-state=4
#resilience4j.circuitbreaker.configs.defecto.slow-call-rate-threshold=50
#resilience4j.circuitbreaker.configs.defecto.slow-call-duration-threshold=2s
#resilience4j.circuitbreaker.instances.items.base-config=defecto
 
#resilience4j.timelimiter.configs.defecto.timeout-duration=2s
#resilience4j.timelimiter.instances.items.base-config=defecto


resilience4j:
  circuitbreaker:
    configs:
      por-defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:      items:
        base-config: por-defecto
  timelimiter:    configs:      por-defecto:
        timeout-duration: 2s
    instances:      items:
        base-config: por-defecto
